/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.etec.exercicio.loja.client.view.clientes;

import br.com.etec.exercicio.loja.client.action.CadastrarClienteAction;
import br.com.etec.exercicio.loja.client.constantes.ConstantesNomenclaturas;
import br.com.etec.exercicio.loja.client.constantes.clientes.ConstantesBotoesClientesView;
import br.com.etec.exercicio.loja.client.controller.ClienteViewController;

/**
 *
 * @author fernando-pucci
 */
public class CadastrarClienteView extends javax.swing.JFrame {

    /**
     * Creates new form TesteFrame
     */
    public CadastrarClienteView() {
        initComponents();
        inicializar();
    }

    private CadastrarClienteAction cadastrarClienteAction;
    private ClienteViewController clienteViewController;

    private void inicializar() {

        this.clienteViewController = new ClienteViewController(this);
        this.cadastrarClienteAction = new CadastrarClienteAction(clienteViewController);
        //
        removeListeners();
        adicionaListeners();

    }

    public String getNome() {
        return jTextFieldNome.getText();

    }

    public String getSobreNome() {
        return jTextFieldSobrenome.getText();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonLimparCliente = new javax.swing.JButton();
        jButtonOkCliente = new javax.swing.JButton();
        jLabelNome = new javax.swing.JLabel();
        jTextFieldNome = new javax.swing.JTextField();
        jTextFieldSobrenome = new javax.swing.JTextField();
        jLabelSobrenome = new javax.swing.JLabel();
        jButtonPesquisar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle(ConstantesNomenclaturas.MENU_CLIENTE_TITLE_MESSAGE);
        setAlwaysOnTop(true);
        setName("CadastrarClenteFrame"); // NOI18N
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonLimparCliente.setText("Limpar");
        jButtonLimparCliente.setName(ConstantesBotoesClientesView.BUTTON_LIMPAR_CLIENTE_MAIN);
        getContentPane().add(jButtonLimparCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 400, 72, -1));

        jButtonOkCliente.setText("OK");
        jButtonOkCliente.setName(ConstantesBotoesClientesView.BUTTON_SALVAR_CLIENTE_MAIN);
        getContentPane().add(jButtonOkCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 400, 72, -1));

        jLabelNome.setText("Nome:");
        getContentPane().add(jLabelNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 20, -1, -1));
        getContentPane().add(jTextFieldNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 40, 190, -1));
        getContentPane().add(jTextFieldSobrenome, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 40, 190, -1));

        jLabelSobrenome.setText("Sobrenome:");
        getContentPane().add(jLabelSobrenome, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 20, 100, -1));

        jButtonPesquisar.setText("Pesquisar...");
        jButtonPesquisar.setName(ConstantesBotoesClientesView.BUTTON_PESQUISAR_CLIENTE_MAIN
        );
        getContentPane().add(jButtonPesquisar, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 40, 100, -1));

        setSize(new java.awt.Dimension(925, 488));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     *//*
     public static void main(String args[]) {
     /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
     * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
     */
    /*
     try {
     for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
     if ("Nimbus".equals(info.getName())) {
     javax.swing.UIManager.setLookAndFeel(info.getClassName());
     break;
     }
     }
     } catch (ClassNotFoundException ex) {
     java.util.logging.Logger.getLogger(TesteFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
     } catch (InstantiationException ex) {
     java.util.logging.Logger.getLogger(TesteFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
     } catch (IllegalAccessException ex) {
     java.util.logging.Logger.getLogger(TesteFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
     } catch (javax.swing.UnsupportedLookAndFeelException ex) {
     java.util.logging.Logger.getLogger(TesteFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
     }
     //</editor-fold>

     /* Create and display the form */
    /*
     java.awt.EventQueue.invokeLater(new Runnable() {
     public void run() {
     new TesteFrame().setVisible(true);
     }
     });
     }*/

    private void removeListeners() {
        jButtonLimparCliente.removeMouseListener(cadastrarClienteAction);
        jButtonOkCliente.removeMouseListener(cadastrarClienteAction);
        jButtonPesquisar.removeMouseListener(cadastrarClienteAction);

    }

    private void adicionaListeners() {
        jButtonLimparCliente.addMouseListener(cadastrarClienteAction);
        jButtonOkCliente.addMouseListener(cadastrarClienteAction);
        jButtonPesquisar.addMouseListener(cadastrarClienteAction);

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonLimparCliente;
    private javax.swing.JButton jButtonOkCliente;
    private javax.swing.JButton jButtonPesquisar;
    private javax.swing.JLabel jLabelNome;
    private javax.swing.JLabel jLabelSobrenome;
    private javax.swing.JTextField jTextFieldNome;
    private javax.swing.JTextField jTextFieldSobrenome;
    // End of variables declaration//GEN-END:variables
}
